SELECT EMP_ID, FIRST_NAME, MID_NAME_INT, LAST_NAME, EMP_START_DATE, GOLD_ENR_DATE
FROM
    /*Isolate employees that are also members*/
    (SELECT EMP_ID, START_DATE AS EMP_START_DATE, ENROLLMENT_DATE AS GOLD_ENR_DATE
    FROM EMPLOYEE
    LEFT OUTER JOIN MEMBER ON MEM_ID = EMP_ID
    WHERE ENROLLMENT_DATE IS NOT NULL)
LEFT OUTER JOIN PERSON ON ID = EMP_ID

/*Another calculation to determine if employee has became a member within a month of
being hired. 1 = 1 MONTH (30 DAYS)*/
WHERE MONTHS_BETWEEN (TO_DATE(MEMBER.ENROLLMENT_DATE), TO_DATE(EMPLOYEE.START_DATE)) <= 1 AND
MONTHS_BETWEEN (TO_DATE(MEMBER.ENROLLMENT_DATE), TO_DATE(EMPLOYEE.START_DATE)) >= 0