/*9. Find the names of members who borrowed the most popular books.*/

SELECT BORROWER_ID, FIRST_NAME, MID_NAME_INT, LAST_NAME
FROM
        (SELECT BOOK_ID AS POP_BOOK_ID
        FROM POPULARBOOKS)
LEFT OUTER JOIN BORROW_DETAILS ON BORROW_DETAILS.BOOK_ID = POP_BOOK_ID
LEFT OUTER JOIN PERSON ON ID = BORROWER_ID
GROUP BY BORROWER_ID, FIRST_NAME, MID_NAME_INT, LAST_NAME
