/*11. Find the name of members who have been a silver member for over 5 years (1800 DAYS)*/

SELECT FIRST_NAME, MID_NAME_INT, LAST_NAME
FROM SILVER_MEMBER
LEFT OUTER JOIN MEMBER ON MEM_ID = SILVER_MEMBER.ID
LEFT OUTER JOIN PERSON ON PERSON.ID = MEM_ID
WHERE MEMBER.ENROLLMENT_DATE NOT between CURRENT_DATE-1800
and CURRENT_DATE