--------------------------------------------------------
--  Ref Constraints for Table BORROW_DETAILS
--------------------------------------------------------

  ALTER TABLE "BORROW_DETAILS" ADD CONSTRAINT "BORROW_DETAILS_FK3_BOR" FOREIGN KEY ("BORROWER_ID")
	  REFERENCES "PERSON" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BORROW_DETAILS" ADD CONSTRAINT "BORROW_DETAILS_FK2_REC" FOREIGN KEY ("RECEPTIONIST_ID")
	  REFERENCES "RECEPTIONISTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BORROW_DETAILS" ADD CONSTRAINT "BORROW_DETAILS_FK2" FOREIGN KEY ("PAYMENT_ID")
	  REFERENCES "PAYMENT_DETAILS" ("PAYMENT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BORROW_DETAILS" ADD CONSTRAINT "BORROW_DETAILS_FK1" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "BOOKS" ("BOOK_ID") ON DELETE CASCADE ENABLE;
