--------------------------------------------------------
--  Constraints for Table BORROW_DETAILS
--------------------------------------------------------

  ALTER TABLE "BORROW_DETAILS" MODIFY ("RECEPTIONIST_ID" NOT NULL ENABLE);
  ALTER TABLE "BORROW_DETAILS" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "BORROW_DETAILS" MODIFY ("BORROWER_ID" NOT NULL ENABLE);
  ALTER TABLE "BORROW_DETAILS" MODIFY ("CHECKOUT_DATE" NOT NULL ENABLE);
  ALTER TABLE "BORROW_DETAILS" MODIFY ("BORROW_ID" NOT NULL ENABLE);
  ALTER TABLE "BORROW_DETAILS" ADD CONSTRAINT "BORROW_DETAILS_PK" PRIMARY KEY ("BORROW_ID")
  USING INDEX  ENABLE;
