--------------------------------------------------------
--  File created - Monday-April-25-2022   
--------------------------------------------------------
@C:\Users\Zedahkai\Desktop\DBProjectSQL\AUTHORS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\BOOKS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\BORROW_DETAILS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\CATALOGING_MANAGERS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\CATALOG_MANAGERS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\EMPLOYEE.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\GOLD_MEMBER.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\GUEST.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\LIBRARY_CARD.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\LIBRARY_SUPERVISORS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\MEMBER.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\PAYMENT_DETAILS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\PAYMENT_METHOD.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\PERSON.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\PUBLISHERS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\RECEPTIONISTS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\RECORDS.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\SILVER_MEMBER.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\AUTHORS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\BOOKS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\BORROW_DETAILS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\CATALOGING_MANAGERS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\CATALOG_MANAGERS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\EMPLOYEE_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\GOLD_MEMBER_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\GUEST_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\LIBRARY_CARD_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\LIBRARY_SUPERVISORS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\MEMBER_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\PAYMENT_DETAILS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\PAYMENT_METHOD_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\PERSON_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\PUBLISHERS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\RECEPTIONISTS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\RECORDS_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\SILVER_MEMBER_CONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\BOOKS_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\BORROW_DETAILS_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\CATALOGING_MANAGERS_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\EMPLOYEE_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\GOLD_MEMBER_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\LIBRARY_CARD_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\LIBRARY_SUPERVISORS_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\MEMBER_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\RECEPTIONISTS_REFCONSTRAINT.sql
@C:\Users\Zedahkai\Desktop\DBProjectSQL\SILVER_MEMBER_REFCONSTRAINT.sql
